homepage:
  path: /
  defaults: { _controller: StikmenRegBundle:Default:index }

contact:
  path: /contact
  defaults: { _controller: StikmenRegBundle:Default:contact }

login:
  path: /login
  defaults: { _controller: StikmenRegBundle:Default:login }

login_check:
  path: /login_check

logout:
  path: /logout

events:
  path: /events
  defaults: { _controller: StikmenRegBundle:Events:index }
  methods: [GET]

events_create:
  path: /events/create
  defaults: { _controller: StikmenRegBundle:Events:create }

events_store:
  path: /events
  defaults: { _controller: StikmenRegBundle:Events:store }
  methods: [POST]

events_show:
  path: /events/{id}/
  defaults: { _controller: StikmenRegBundle:Events:show, id: 1 }
  methods: [GET]

events_edit:
  path: /events/{id}/edit
  defaults: { _controller: StikmenRegBundle:Events:edit, id: 1 }

events_update:
  path: /events/{id}/
  defaults: { _controller: StikmenRegBundle:Events:update, id: 1 }
  methods: [PUT]

events_destroy:
  path: /events/{id}/
  defaults: { _controller: StikmenRegBundle:Events:destroy, id: 1 }
  methods: [DELETE]

users:
  path: /users
  defaults: { _controller: StikmenRegBundle:Users:index }
  methods: [GET]

users_create:
  path: /users/create
  defaults: { _controller: StikmenRegBundle:Users:create }
  methods: [GET]

users_store:
  path: /users
  defaults: { _controller: StikmenRegBundle:Users:store }
  methods: [POST]

users_show:
  path: /users/{id}/
  defaults: { _controller: StikmenRegBundle:Users:show, id: 1 }
  methods: [GET]

users_edit:
  path: /users/{id}/edit
  defaults: { _controller: StikmenRegBundle:Users:edit, id: 1 }

users_update:
  path: /events/{id}/
  defaults: { _controller: StikmenRegBundle:Users:update, id: 1 }
  methods: [PUT]

users_destroy:
  path: /users/{id}/
  defaults: { _controller: StikmenRegBundle:Users:destroy, id: 1 }
  methods: [DELETE]
