homepage:
  path: /
  defaults: { _controller: StikmenRegBundle:Default:index }

contact:
  path: /contact
  defaults: { _controller: StikmenRegBundle:Default:contact }

login:
  path: /login
  defaults: { _controller: StikmenRegBundle:Default:login }

login_check:
  path: /login_check

logout:
    path: /logout

events:
  path: /events
  defaults: { _controller: StikmenRegBundle:Events:index }
  methods: [GET]

events_create:
  path: /events/create
  defaults: { _controller: StikmenRegBundle:Events:create }

events_store:
  path: /events
  defaults: { _controller: StikmenRegBundle:Events:store }
  methods: [POST]

events_show:
  path: /events/{id}
  defaults: { _controller: StikmenRegBundle:Events:show }
  methods: [GET]

events_edit:
  path: /events/{id}/edit
  defaults: { _controller: StikmenRegBundle:Events:edit }

events_update:
  path: /events/{id}
  defaults: { _controller: StikmenRegBundle:Events:update }
  methods: [PUT]

events_destroy:
  path: /events/{id}
  defaults: { _controller: StikmenRegBundle:Events:destroy }
  methods: [DELETE]

users:
  path: /users
  defaults: { _controller: StikmenRegBundle:Users:index }
  methods: [GET]

users_create:
  path: /users/create
  defaults: { _controller: StikmenRegBundle:Users:create }
  methods: [GET]

users_store:
  path: /users
  defaults: { _controller: StikmenRegBundle:Users:store }
  methods: [POST]
