parameters:
#    stikmen_reg.example.class: Stikmen\RegBundle\Example

services:
#    stikmen_reg.example:
#        class: %stikmen_reg.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
